#version: "3.8"
services:
  base:
    image: bot-base-image:latest
    container_name: bot-base-container
    build:
      context: .
      dockerfile: docker-files/bot-base-image.dockerfile
    environment:
      - POETRY_VIRTUALENVS_CREATE=false
  bot:
    image: bot-main-image:latest
    container_name: bot-main-container
    build:
      context: .
      dockerfile: docker-files/bot-main-image.dockerfile
    env_file:
      - docker-files/main_image.env
    depends_on:
      - base
    ports:
      - 6379:6379