#version: "3.8"

services:
  bot:
    image: bot-dev:latest
    container_name: bot-dev-container
    build:
      context: ../..
      dockerfile: docker-files/dev/bot-dev.dockerfile
    volumes:
      - ../..:/home/bot:rw
    depends_on:
      - fsm
      - postgres

  fsm:
    image: redis:alpine
    container_name: redis-bot-dev
    hostname: fsm
    restart: always
    command: redis-server # --save 20 1 --loglevel info
    env_file:
      - redis_dev.env
    ports:
      - '5190:6379'
    volumes:
      - redis_dev_data:/data

  postgres:
    image: postgres:alpine
    container_name: postgres-bot-dev
    hostname: postgres
    restart: always
    env_file:
      - postgres_dev.env
    ports:
      - '7920:5432'
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data

volumes:
  redis_dev_data:
    driver: local
  postgres_dev_data:
    driver: local

#networks:
#  bot:
#    driver: host