#version: "3.8"

services:
  fsm:
    image: redis:alpine
    container_name: redis-fsm-dev
    hostname: fsm
    restart: always
    command: redis-server # /etc/redis.conf # --save 20 1 --loglevel info
    ports:
      - '6379:6379'
    volumes:
      - ./redis-fsm-dev.conf:/etc/redis.conf
      - redis_dev_data:/data

  postgres:
    image: postgres:alpine
    container_name: postgres-dev
    hostname: postgres
    restart: always
    command: postgres -c config_file=/etc/postgresql.conf
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=bot_dev_db
    ports:
      - '5432:5432'
    volumes:
      - ./postgresql-dev.conf:/etc/postgresql.conf
      - postgres_dev_data:/var/lib/postgresql/data

volumes:
  redis_dev_data:
    driver: local
  postgres_dev_data:
    driver: local