#version: "3.8"
services:
  base:
    image: base-image:latest
    #    container_name: base-image-container
    build:
      context: .
      dockerfile: base-image.dockerfile

  debug:
    image: bot-debug-image:latest
    container_name: bot-debug-container
    build:
      context: ..
      dockerfile: docker-files/debug/bot-debug-image.dockerfile
    volumes:
      - ../:/home/bot:rw
    env_file: debug/bot_debug_image.env
    depends_on:
      - base

  release:
    image: bot-release-image:latest
    container_name: bot-release-container
    build:
      context: ..
      dockerfile: docker-files/release/release-image.dockerfile
    env_file: release/release_image.env
    depends_on:
      - base
    volumes:
      - ../pgdata:/var/lib/postgresql/data:rw