#version: "3.8"
services:
  bot:
    image: bot-prod:latest
    container_name: bot-prod-container
    build:
      context: ../..
      dockerfile: docker-files/prod/bot-prod.dockerfile
    networks:
      - bot
    depends_on:
      - fsm
      - postgres

  fsm:
    image: redis:alpine
    container_name: redis-bot-prod
    hostname: fsm
    restart: always
    command: redis-server # --save 20 1 --loglevel info  --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    env_file:
      - redis_prod.env
    networks:
      - bot
    volumes:
      - redis_prod_data:/data

  postgres:
    image: postgres:alpine
    container_name: postgres-bot-prod
    hostname: postgres
    restart: always
    env_file:
      - postgres_prod.env
    networks:
      - bot
    
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data

volumes:
  redis_prod_data:
    driver: local
  postgres_prod_data:
    driver: local

networks:
  bot:
    driver: bridge