#version: "3.8"
services:
  bot:
    image: bot-prod:latest
    container_name: bot-prod
    build:
      context: ../..
      dockerfile: docker-files/prod/bot-prod.dockerfile
    depends_on:
      - fsm
      - postgres

  fsm:
    image: redis:alpine
    container_name: redis-fsm-prod
    hostname: fsm
    restart: always
    command: redis-server # /etc/redis.conf # --requirepass l4XeAeCn4RYOg0E7 # --save 20 1 --loglevel info
    ports:
      - '5201:6379'
    volumes:
      - ./redis-fsm-prod.conf:/etc/redis.conf
      - redis_prod_data:/data

  postgres:
    image: postgres:alpine
    container_name: postgres-prod
    hostname: postgres
    restart: always
    command: postgres -c config_file=/etc/postgresql.conf
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_DB=bot_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=3Ep81a1AhE
      - POSTGRES_INITDB_ARGS="--auth-host=scram-sha-256 --auth-local=scram-sha-256"
    ports:
      - '6549:5432'
    volumes:
      - ./postgresql-prod.conf:/etc/postgresql.conf
      - postgres_prod_data:/var/lib/postgresql/data

volumes:
  redis_prod_data:
    driver: local
  postgres_prod_data:
    driver: local
